### ISSUE TITLE
required packages

### ISSUE THREAD

**Issue by vn971** [aochagavia/Serve#5]
What packages are required to build Serve? I tried to build Serve locally but compilation failed:

> /target/debug/build/openssl-sys-e0bd245bf09b1a3f/build-script-build` (exit code: 101)
> 
> running: "cc" "-O0" "-c" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-fPIC" "-o" "/home/vasya/data/dev/rust/serve-current-directory/target/debug/build/openssl-sys-e0bd245bf09b1a3f/out/src/openssl_shim.o" "src/openssl_shim.c"
> 
> command did not execute successfully, got: exit code: 1
> 
> src/openssl_shim.c:1:26: fatal error: openssl/hmac.h: No such file or directory
>  #include <openssl/hmac.h>

I do have `openssl` installed, although I'm not sure about any development files for it (I don't know).

**Comment by aochagavia** [comment]
It looks like cargo is unable to build `openssl-sys`. Maybe you could try following the instructions on the library's [repo](https://github.com/sfackler/rust-openssl). Good luck!

**Comment by vn971** [comment]
@aochagavia thanks, that worked!
I needed the `libssl-dev` package described in `rust-openssl` repo.

And I could not force Serve to somehow show the content of a parent dir.. Cool.)

**Comment by aochagavia** [comment]
The credits goes to `Iron` and `staticfile`... As you can see in the source code, this application is mostly a wrapper around those libraries. :wink:

**Comment by vn971** [comment]
Yeah.)

**Comment by vn971** [comment]
@aochagavia BTW, I now see that directories are being redirected with HTTP status code 301, which means "moved permanently".
So, any subsequent browser requests will be made to the referenced URL. This seems bad for an app that is launched from many different locations on a popular address localhost:8080 (something that was a redirection may stop be such).
I dunno if I should open a separate ticket for that, and where (`iron`?).

**Comment by aochagavia** [comment]
I think you should report it at the [staticfile](https://github.com/iron/staticfile) repo. That is the Iron module related to static file serving. I think the problem lies [here](https://github.com/iron/staticfile/blob/master/src/static_handler.rs#L118)
