### ISSUE TITLE
Feature request: directory listing

### ISSUE THREAD

**Issue by gaveen** [aochagavia/Serve#7]
In #2 I leaned that Serve doesn't do directory listings, it just serves individual files.

This is a suggestion that directory listing would be a much nice to have. It'll make things easier to be discovered by the person accessing than being explicitly given the URL by the runner of the command.

Unfortunately I have no idea where even to start with to implement a feature like that for this project (e.g., maybe from Iron side?). So, opening a ticket someone interested may implement it.

**Comment by aochagavia** [comment]
Iron is a very modular framework, so you shouldn't need to edit it directly. `Serve` uses the `staticfile` crate, which is a handler for Iron that serves static files but doesn't do directory listing. I see two alternatives:
1. Extend `staticfile` to have a directory listing feature.
2. Create a new Iron handler that relies on `staticfile` to serve files and has a fallback to directory listing when `staticfile` fails.

Unfortunately I don't have time to implement this right now, but I can answer any questions :smile:

**Comment by aochagavia** [comment]
As stated in https://github.com/iron/staticfile/issues/53#issuecomment-144840067, alternative 1 seems to be a valid approach.
